### ISSUE TITLE
I know this is realllly old, but...

### ISSUE THREAD

**Issue by Krutonium** [blha303/ShadowBan#2]
Can you update to the latest bukkit (spigot now I guess) and also make shadow banned players modifications to the world be visible to only them?

**Comment by blha303** [comment]
I didn't think anyone still used any of my plugins :D Does it work? What doesn't work?

**Comment by Krutonium** [comment]
I haven't tried it, but it is pretty much guaranteed after 2 years that it doesn't work XD

I'll fire up my test server and see if it runs.

**Comment by blha303** [comment]
It almost definitely does work, because it only uses the Bukkit api.

**Comment by Krutonium** [comment]
o.0 So apparently it does work, but you have to run the server twice... The first time you run it, it spews an error. After that it works.

About my second request... Possible?

**Comment by blha303** [comment]
... Any chance you could [paste the error](https://gist.github.com)?

And no, I don't know how I'd do that, and I haven't made bukkit plugins since Sep 2013.

**Comment by Krutonium** [comment]
Unfortunately not, though I can probably reproduce it, hold on.

**Comment by blha303** [comment]
It'd be in the server log

**Comment by Krutonium** [comment]
https://gist.github.com/PFCKrutonium/c79829f301654e1f787c

**Comment by Krutonium** [comment]
But as I said, the second time you run the server, the error doesn't occur.

**Comment by blha303** [comment]
Because at that point it generates the config and it's there (in ShadowBan/config.yml). If the plugin works as expected I'm going to go ahead and close this issue.

**Comment by blha303** [comment]
And thanks for using ShadowBan, I've always thought it was a cool function Minecraft needs :P

**Comment by Krutonium** [comment]
And so do I ;P
